### ISSUE TITLE
Error message when installing from melpa

### ISSUE THREAD

**Issue by csantosb** [emacs-helm/helm-recoll#10]
I get 
    
    Debugger entered--Lisp error: (void-variable dir)

in line

    (format "Source for retrieving files matching the current input pattern\nusing recoll with the configuration in \"%s\"." dir)

Can you confirm ?

**Comment by michael-heerdegen** [comment]
What does "when installing from Melpa" mean?

I installed the version from Melpa and did not get an error.  I then loaded the file and evaluated one of the examples creating a source, and did not get an error neither.

Recipe?

**Comment by michael-heerdegen** [comment]
I see now how this can happen - when you evaluate a definition with lexical-binding off.  Will push a fix soon, thanks.

**Comment by michael-heerdegen** [comment]
Can you confirm it's fixed @csantosb ?

**Comment by csantosb** [comment]
Fixed now, thanks !
