### ISSUE TITLE
Only first word is used as a search term. Second+ words are used to filter helm window.

### ISSUE THREAD

**Issue by Demosthenexx** [emacs-helm/helm-recoll#18]
Clearly helm-recoll intended to split the pattern string as that call is there.

https://github.com/emacs-helm/helm-recoll/blob/master/helm-recoll.el#L266

Has helm's behavior changed?

**Comment by thierryvolpiatto** [comment]
Demosthenexx <notifications@github.com> writes:

> Clearly helm-recoll intended to split the pattern string as that call is there.
>
> https://github.com/emacs-helm/helm-recoll/blob/master/helm-recoll.el#L266
>
> Has helm's behavior changed?

No, helm-recoll works as expected, use C-h m to see how it works.
You can add queries separated by spaces, but these queries are recoll
queries, not partial completion pattern like you may use in other parts
of helm.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Demosthenexx** [comment]
I am relatively new to helm. However I've repeatedly read that help, did an hour of googling and IRC, and eventually put message outputs into helm-recoll to dump the search term received by the function to confirm what I was seeing.

The experience I had was that my first word was used for a recoll query, and the second word was used by helm to filter the results. I have been unable to add a longer multi-word recoll query thru use of other characters, quoting, the '-o' option at the top of your help, etc. Is there a magic feature I'm missing?

**Comment by thierryvolpiatto** [comment]
Demosthenexx <notifications@github.com> writes:

> The experience I had was that my first word was used for a recoll
> query, and the second word was used by helm to filter the results. I
> have been unable to add a longer multi-word recoll query thru use of
> other characters, quoting, the '-o' option at the top of your help,
> etc. Is there a magic feature I'm missing?

Yes, helm-recoll is using match-dynamic helm feature, that's mean none
of the helm match functions are called, only relaying on recoll to fetch
candidates, i.e. on the helm :candidates function specified in
`helm-recoll-source`.

Perhaps you can provide concrete examples (recipes) where helm-recoll
fails so that I can reproduce and find what's wrong.

Thanks.
 
-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Demosthenexx** [comment]
I have three existing Recoll libraries, and currently use the terminal with a simple dialog based script to find content. I'll use recollq for my examples.


Query my redbook archive, just "aix", first few results and the count of the results (330).

> % recollq -c ~/Library/.recoll-Technical -q aix | head  
> :3:common/rclinit.cpp:312::Configuration directory: /home/adamsrl/Library/.recoll-Technical
> Recoll query: Query(((aix OR aix's OR aixes) OR aix#10))
> 328 results
> application/pdf	[file:///home/adamsrl/Library/Technical/2018/08/13/Simplified Remote Restart White Paper.pdf]	[Simplified Remote Restart White Paper.pdf]	1757381	bytes	
> text/html	[file:///home/adamsrl/Library/Technical/2015/11/19/PrintingAtoZ.html]	[AIX A-Z: Managing printing on AIX AIX A-Z: Managing printing on AIX]	78283	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2016/07/18/vcs_bundled_agents_51sp1pr1_aix.pdf]	[Veritas Cluster Server 5.1 SP1 PR1 Bundled Agents Reference Guide - AIX]	1937879	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/sg246050.pdf]	[SG246050.book]	3624226	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2016/06/02/sg247940.pdf]	[IBM PowerVM Virtualization Introduction and Configuration]	7808966	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/sg246769.pdf]	[Implementing High Availability Clustering Multi-Processing (HACMP) Cookbook]	7105893	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/Integrating AIX into Heterogenous LDAP Environments - IBM.pdf]	[Integrating AIX into Heterogenous LDAP Environments]	3910140	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/sg247165.pdf]	[Integrating AIX into Heterogenous LDAP Environments]	3910140	bytes	
> 
> % recollq -c ~/Library/.recoll-Technical -q aix | wc -l
> :3:common/rclinit.cpp:312::Configuration directory: /home/adamsrl/Library/.recoll-Technical
> 330

Query my redbook archive, "aix" or "bash", and the result count (335) .

> % recollq -c ~/Library/.recoll-Technical -q aix OR bash | head
> :3:common/rclinit.cpp:312::Configuration directory: /home/adamsrl/Library/.recoll-Technical
> Recoll query: Query((((aix OR aix's OR aixes) OR aix#10) OR ((bash OR bashful) OR bash#10)))
> 333 results
> text/html	[file:///home/adamsrl/Library/Technical/2015/11/19/PrintingAtoZ.html]	[AIX A-Z: Managing printing on AIX AIX A-Z: Managing printing on AIX]	78283	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/sg246033.pdf]	[SG246033.book]	4955525	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/Oracle Database Administrator's Reference for Linux and UNIX-Based Operating Systems - Oracle Corporation.pdf]	[Oracle Database Administrator’s Reference for Linux and UNIX-Based Operating Systems]	1871102	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/IBM System Storage DS8000_ Host Attachment and Interoperability - IBM.pdf]	[IBM System Storage DS8000: Host Attachment and Interoperability]4962023	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/sg247165.pdf]	[Integrating AIX into Heterogenous LDAP Environments]	3910140	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/Integrating AIX into Heterogenous LDAP Environments - IBM.pdf]	[Integrating AIX into Heterogenous LDAP Environments]	3910140	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/sg246786.pdf]	[IBM System Storage DS8000 Series: Architecture and Implementation]	10124438	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/IBM System Storage DS8700 Architecture and Implementation - IBM.pdf]	[IBM System Storage DS8700 Architecture and Implementation]	14311649bytes	
> 
> % recollq -c ~/Library/.recoll-Technical -q aix OR bash | wc -l
> :3:common/rclinit.cpp:312::Configuration directory: /home/adamsrl/Library/.recoll-Technical
> 335

Query my redbook archive, "aix" and "bash", and the result count (33).

> % recollq -c ~/Library/.recoll-Technical -q aix AND bash | head
> :3:common/rclinit.cpp:312::Configuration directory: /home/adamsrl/Library/.recoll-Technical
> Recoll query: Query((((aix OR aix's OR aixes) OR aix#10) AND ((bash OR bashful) OR bash#10)))
> 31 results
> text/html	[file:///home/adamsrl/Library/Technical/2015/11/19/PrintingAtoZ.html]	[AIX A-Z: Managing printing on AIX AIX A-Z: Managing printing on AIX]	78283	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/sg246033.pdf]	[SG246033.book]	4955525	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/Oracle Database Administrator's Reference for Linux and UNIX-Based Operating Systems - Oracle Corporation.pdf]	[Oracle Database Administrator’s Reference for Linux and UNIX-Based Operating Systems]	1871102	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/IBM System Storage DS8000_ Host Attachment and Interoperability - IBM.pdf]	[IBM System Storage DS8000: Host Attachment and Interoperability]4962023	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/sg247165.pdf]	[Integrating AIX into Heterogenous LDAP Environments]	3910140	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/Integrating AIX into Heterogenous LDAP Environments - IBM.pdf]	[Integrating AIX into Heterogenous LDAP Environments]	3910140	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/sg246786.pdf]	[IBM System Storage DS8000 Series: Architecture and Implementation]	10124438	bytes	
> application/pdf	[file:///home/adamsrl/Library/Technical/2015/11/19/IBM System Storage DS8700 Architecture and Implementation - IBM.pdf]	[IBM System Storage DS8700 Architecture and Implementation]	14311649bytes	
> 
> % recollq -c ~/Library/.recoll-Technical -q aix AND bash | wc -l
> :3:common/rclinit.cpp:312::Configuration directory: /home/adamsrl/Library/.recoll-Technical
> 33

Using helm-recoll for my technical library (recollq honored as executable, and -c works), at the helm prompt I use the bare word "aix" without quotes, and I receive 121 results like this:

> Recoll Technical
> PrintingAtoZ.html
> vcs_bundled_agents_51sp1pr1_aix.pdf
> Integrating AIX into Heterogenous LDAP Environments - IBM.pdf
> sg247165.pdf
> IBM AIX Version 6.1 Differences Guide - IBM.pdf
> sg247559.pdf
> EMC Host Connectivity Guide for IBM AIX_20110828.pdf
> EMC Host Connectivity Guide for IBM AIX - Roseanne Ouellette.pdf
> IBM PowerHA SystemMirror 7.1 for AIX - IBM.pdf
> sg247845.pdf
> AIX V6 Advanced Security Features: Introduction and Configuration_20121205094153.pdf
> AIX Version 5.3_ Security - IBM.pdf

Which is ok. Now if I add the bare word "bash" without quotes so my complete bottom line in helm reads "pattern: aix bash", there are zero results. Zero results for "aix OR bash", none for "aix AND bash". Zero results for "-o aix". Etc.

If I start with the first term "aix", and start typing the "b" for bash, I can see the results filter to only those items with a b in the helm buffer. I conclude that helm isn't passing the second word to helm-collect, either due to my inexperience or misconfiguration. I confirmed this in helm-collect by adding a message output to print helm-pattern when the function to compose the command string is run at:

https://github.com/emacs-helm/helm-recoll/blob/master/helm-recoll.el#L270  in function helm-recoll--setup-cmd. When that function is invoked, helm-pattern is the string "aix" and never more. The split only has one word to work on.

I'm seeing other feedback on stackoverflow and other tickets that helm may struggle with space interpretation and patterns, but couldn't find much.

Again, I think this is due to either my inexperience or a helm behavior as helm-recoll seems to have the right logic in place. Do you have an example of a search string which included spaces that worked for you?

If you'd like a more real time discussion, I'm in several Emacs channels on Freenode.

**Comment by thierryvolpiatto** [comment]
Demosthenexx <notifications@github.com> writes:

>
> https://github.com/emacs-helm/helm-recoll/blob/master/helm-recoll.el#L270
> in function helm-recoll--setup-cmd. When that function is invoked,
> helm-pattern is the string "aix" and never more. The split only has
> one word to work on.

No, helm is taking the two words, you can verify with: 

C-h C-d C-! before entering your pattern
Enter your pattern and hit again C-!
And then C-g to quit
And M-x helm-debug-open-last-log

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Demosthenexx** [comment]
I see in the helm debug output the two words, but only when I do the C-! for helm suspending the updates.

See this: https://asciinema.org/a/n1VEvNSEFj4NT0saePSWapkze

**Comment by thierryvolpiatto** [comment]
Demosthenexx <notifications@github.com> writes:

> I see in the helm debug output the two words, but only when I do the
> C-! for helm suspending the updates.

Are you sure? I have here the two patterns in the debug log.

> See this: https://asciinema.org/a/n1VEvNSEFj4NT0saePSWapkze

What you show here is not a helm debug log.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment]
![Capture d’écran_2020-08-05_18-51-43](https://user-images.githubusercontent.com/1533939/89441182-0d12a200-d74d-11ea-9130-0762de059498.png)

![Capture d’écran_2020-08-05_18-53-21](https://user-images.githubusercontent.com/1533939/89441205-169c0a00-d74d-11ea-81fa-8127f3330278.png)

**Comment by thierryvolpiatto** [comment]
As you can see there is a lot of false positive, but the reason is that I guess recoll is looking also at the file contents.  Dunno how to disable this (I generally don't use recoll).

I guess you see only one pattern in helm log because you look only at the first command line call.

**Comment by Demosthenexx** [comment]
Like I said, it could be a configuration issue. Or differing versions. I think it's helm, not helm-recoll.

helm 20181120.1326
helm-recoll 20190729.453
emacs 26.1

I'll try upgrading helm. Thing is I took the screen recording because it could reliably reproduce it, and couldn't explain it. I'm glad it's working for you, it gives me hope!

**Comment by thierryvolpiatto** [comment]
Demosthenexx <notifications@github.com> writes:

> Like I said, it could be a configuration issue. Or differing versions. I think it's helm, not helm-recoll.
>
> helm 20181120.1326

Oh! of course, we are using two different beast!
You don't have dynamic completion, I even wonder how it works more or
less, ha! yes because the also old version of helm-recoll!

> helm-recoll 20190729.453

Same here.

> emacs 26.1

And same here, but 26.1 should be ok.

-- 
Thierry

Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by Demosthenexx** [comment]
Just updated to Emacs 27.1, and Helm 202008*, and multiple search terms now work.
