### ISSUE TITLE
More cleanup

### ISSUE THREAD

**Issue by michael-heerdegen** [emacs-helm/helm-recoll#6]
Hello,

here are some more little things to do:

  - update Copyright

  - fix the overlong lines

  - use classes, instead of plain lists, to define sources

**Comment by michael-heerdegen** [comment]
Well, we have made some progress.  This is what's left:

  - add email addresses of MH and CS in the header
  - fix the overlong lines in the "helm-recoll-help-message"
  - Make a class for "helm-recoll-sources-source"

**Comment by csantosb** [comment]
>Well, we have made some progress.  This is what's left:
>
>  - add email addresses of MH and CS in the header
>  - fix the overlong lines in the "helm-recoll-help-message"
>  - Make a class for "helm-recoll-sources-source"

I'll take care of first two.

**Comment by michael-heerdegen** [comment]
Thanks.  Now only

 - Make a class for "helm-recoll-sources-source"

is left.

**Comment by michael-heerdegen** [comment]
Done.
